Import('env')

src_files = Glob('*.cpp') + Glob('common/*.cpp')

btx_sdk = env.SharedLibrary(target="botson_sdk",
                            source=src_files,
                            LIBS=['GL', 'jpeg', 'png'],
                            SHLIBVERSION="1.1.1")

env.InstallLibs('install', btx_sdk)

