Import('env')

src_files = Glob('*.cpp') + Glob('common/*.[ct]pp')

btx_sdk = env.SharedLibrary(target="SDK",
                            source=src_files,
                            LIBS=['GL', 'jpeg', 'png'],
                            SHLIBVERSION="1.1.1")

env.InstallLibs('install', btx_sdk)

